/**
 * Template Permissions
 *
 * Define Action and Entidad // Accion y Entity
 *
 * CREATE_PRODUCT // Crear Producto
 * READ_PRODUCT // Leer Producto
 * UPDATE_PRODUCT // Actualizar Producto
 * DELETE_PRODUCT // Eliminar Producto
 *
 */

enum Permission {
  // ** ALL PERMISSIONS (FOR SUPER ADMIN)
  ALL_PERMISSIONS = 'ALL_PERMISSIONS',

  // ** USER MANAGEMENT
  // ROLE
  CREATE_ROLE = 'CREATE_ROLE',
  READ_ROLE = 'READ_ROLE',
  UPDATE_ROLE = 'UPDATE_ROLE',
  DELETE_ROLE = 'DELETE_ROLE',

  // USER
  CREATE_USER = 'CREATE_USER',
  READ_USER = 'READ_USER',
  UPDATE_USER = 'UPDATE_USER',
  DELETE_USER = 'DELETE_USER',

  // ** COMPANY MANAGEMENT
  // COMPANY
  CREATE_COMPANY = 'CREATE_COMPANY',
  READ_COMPANY = 'READ_COMPANY',
  UPDATE_COMPANY = 'UPDATE_COMPANY',
  DELETE_COMPANY = 'DELETE_COMPANY',

  // ** ENTITIES FOR BUSSINESS

  // CUSTOMER
  CREATE_CUSTOMER = 'CREATE_CUSTOMER',
  READ_CUSTOMER = 'READ_CUSTOMER',
  UPDATE_CUSTOMER = 'UPDATE_CUSTOMER',
  DELETE_CUSTOMER = 'DELETE_CUSTOMER',
  
  // PRODUCT
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  READ_PRODUCT = 'READ_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  DELETE_PRODUCT = 'DELETE_PRODUCT',

  // PAYMENT
  CREATE_PAYMENT = 'CREATE_PAYMENT',
  READ_PAYMENT = 'READ_PAYMENT',
  UPDATE_PAYMENT = 'UPDATE_PAYMENT',
  DELETE_PAYMENT = 'DELETE_PAYMENT',

  // ORDER
  CREATE_ORDER = 'CREATE_ORDER',
  READ_ORDER = 'READ_ORDER',
  UPDATE_ORDER = 'UPDATE_ORDER',
  DELETE_ORDER = 'DELETE_ORDER',

  // CREDIT
  CREATE_CREDIT = 'CREATE_CREDIT',
  READ_CREDIT = 'READ_CREDIT',
  UPDATE_CREDIT = 'UPDATE_CREDIT',
  DELETE_CREDIT = 'DELETE_CREDIT',

  // BALANCE
  CREATE_BALANCE = 'CREATE_BALANCE',
  READ_BALANCE = 'READ_BALANCE',
  UPDATE_BALANCE = 'UPDATE_BALANCE',
  DELETE_BALANCE = 'DELETE_BALANCE',
  
}

// ** EXPORT PERMISSIONS LIST
export const permissions = {
  ...Permission,
}

export default Permission

export interface PermissionObject {
  [key: string]: string
}

export type KeyPermissionsType = keyof typeof Permission
